sudo: false
language: node_js

node_js:
  - '5'
  - '4'
  - '0.12'
  - '0.10'

cache:
  directories:
  - node_modules

services:
- mysql

before_script:
  - mysql -h localhost -u root --password="" < ./script/schema.sql

after_script:
  npm run coverage
